### ISSUE TITLE
Backend breaks after extension installation

### ISSUE THREAD

**Issue by Ioan-Popa** [Dominik-Sch/skins#4]
After installing the extension on a TYPO3 11.5.14, the backend showed the following:

**(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception**

`PHP Warning: Undefined array key "tx_skins_darkmode" in /var/www/vhost0/cms/typo3conf/ext/skins/Classes/Hooks/PageRenderer.php line 31`

Any idea why?

The only thing I could do was to manually deactivate the extension.

Thank you.

**Comment by Dominik-Sch** [comment]
@Ioan-Popa do you have any other 3th party extensions installed?

I can't reproduce this error on a clean installation.
Tested on version 11.5.14 and 11.5.15 today.

**Comment by Ioan-Popa** [comment]
Thank you for looking into it.

I have some extensions now, but at the time of trying yours I think the TYPO3 11.5.14 instance was pretty virgin.

Since you mentioned it, I successfully installed the **skins** extension on a TYPO3 11.5.12 instance.

I just tried again on the TYPO3 11.5.14 version and, miracle of miracles, it worked. Hallelujah!

**Comment by Dominik-Sch** [comment]
thx for the reply :) 
hope you like the default skin.
some updates will come in the near feature.
