### ISSUE TITLE
PHP 8.2 und TYPO3 12.4 breaks backend

### ISSUE THREAD

**Issue by josefglatz** [Dominik-Sch/skins#7]
PHP Warning: Undefined array key "tx_skins_dark_mode_settings" in /var/www/html/typo3conf/ext/skins/Classes/Hooks/PageRenderer.php line 28

**Comment by josefglatz** [comment]
How to reproduce:

1. set dark mode
2. press save
3. error appears

**Comment by sunilgknair051** [comment]
I have the same problem but it comes up when I create a new backend user in the admin tools. I am not too sure if this has to interrupt the user creation process.

**Comment by Dominik-Sch** [comment]
@sunilgknair051 this problem should be fixed within the current version (11.1.3)
